# Generated by Django 3.0.5 on 2020-04-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('customers', '0005_auto_20200417_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
    ]
