# Generated by Django 3.0.5 on 2020-04-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200417_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
