# Generated by Django 3.0.5 on 2020-04-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.TextField(default='', max_length=30),
        ),
    ]
