# Generated by Django 3.0.5 on 2020-05-07 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('blogs', '0001_initial'),
        ('customers', '0001_initial'),
        ('metas', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('source', models.TextField(blank=True)),
                ('ping', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[(1, 'post'), (2, 'video'), (3, 'audio'), (4, 'image'), (5, 'other')], default=1, max_length=2)),
                ('status', models.CharField(default='publish', max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
                ('categories', models.ManyToManyField(blank=True, to='categories.Category')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('meta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metas.Meta')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
        ),
    ]
