# Generated by Django 3.0.5 on 2020-05-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('value', models.TextField()),
                ('option', models.TextField()),
                ('isDelete', models.BooleanField(default=False)),
                ('default', models.TextField(default='')),
            ],
        ),
    ]
