# Generated by Django 3.0.5 on 2020-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=30),
        ),
    ]
