# Generated by Django 3.0.5 on 2020-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='data',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
