# Generated by Django 3.0.5 on 2020-07-14 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('html', models.TextField(default='{}')),
                ('status', models.CharField(default='publish', max_length=30)),
                ('isDeleted', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'header'), (2, 'sidebar-default'), (3, 'footer'), (4, 'main-nav'), (5, 'detail')])),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
