# Generated by Django 3.0.5 on 2020-07-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.IntegerField(choices=[(1, 'header'), (2, 'sidebar-default'), (3, 'footer'), (4, 'main-nav'), (5, 'detail')]),
        ),
    ]
