# Generated by Django 3.0.5 on 2020-07-10 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20200710_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
