# Generated by Django 3.0.5 on 2020-07-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
