# Generated by Django 3.0.5 on 2020-07-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200714_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.IntegerField(choices=[(1, 'post'), (2, 'video'), (3, 'audio'), (4, 'image'), (5, 'other')], default=1),
        ),
    ]
