# Generated by Django 3.0.5 on 2020-07-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200723_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.AddField(
            model_name='article',
            name='resource',
            field=models.TextField(blank=True, null=True),
        ),
    ]
