# Generated by Django 3.0.5 on 2020-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonLd', models.TextField(blank=True, default='{}')),
                ('view', models.BigIntegerField(default=0)),
                ('like', models.BigIntegerField(default=0)),
                ('isDelete', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
