# Generated by Django 3.0.5 on 2020-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_meta_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='type',
        ),
        migrations.AddField(
            model_name='meta',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
