# Generated by Django 3.0.5 on 2020-04-19 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_auto_20200419_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='slug',
        ),
    ]
