# Generated by Django 3.0.5 on 2020-04-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='ping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='publish', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
