# Generated by Django 3.0.5 on 2020-04-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
        ('metas', '0001_initial'),
        ('posts', '0004_auto_20200417_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metas.Meta'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(null=True, to='categories.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag'),
        ),
    ]
