# Generated by Django 3.0.5 on 2020-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200417_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
