# Generated by Django 3.0.5 on 2020-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('html', models.TextField(default='{}')),
                ('status', models.CharField(default='publish', max_length=30)),
                ('isDelete', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[(1, 'header'), (2, 'sidebar-default'), (3, 'footer'), (4, 'main-nav'), (5, 'detail')], max_length=2)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
