# Generated by Django 3.0.5 on 2020-07-17 06:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='none', max_length=30)),
                ('title', models.CharField(default='', max_length=30)),
                ('isDeleted', models.BooleanField(default=False)),
                ('image', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('size', models.CharField(max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='metas.Meta')),
            ],
        ),
    ]
