# Generated by Django 3.0.5 on 2020-07-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='isDeleted',
        ),
    ]
